// 包含了多个action的type
export const SAVE_USER = 'save_user'
export const REMOVE_USER = 'remove_user'
export const UPDATE_TITLE = 'update_title'
export const GET_CATEGORIES = 'get_categories'
export const ADD_CATEGORY = 'add_category'
export const UPDATE_CATEGORY = 'update_category'
export const DEL_CATEGORY = 'del_category'
export const GET_ROLES = 'get_roles'
export const ADD_ROLES = 'add_roles'
export const UPDATE_ROLES = 'update_roles'
export const DELETE_ROLES = 'delete_roles'
export const GET_USERS = 'get_users'
export const ADD_USER = 'add_user'
export const UPDATE_USER = 'update_user'
export const DELETE_USER = 'delete_user'
